//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace NetSendWaitCar {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OutServiceSoap11Binding", Namespace="http://outservice.checkinspect.ahkeli.com")]
    public partial class AHOutService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryBaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback recheckRegisterVehicleOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryPcbParaOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqEndCheckProcessOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqYwtbOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryOutlineSizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqEndDetectingOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryVehicleOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqBeginDetectingOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqCaptureOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryPszpAndJyxmOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerVehInfoModifyOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqWriteOtherDataOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryPcbPhotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqWriteRgjyxmDataOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryClWgjyjgOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerVehicleOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqWriteCheckDataOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqBeginCheckProcessOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqWriteEnvInspInfoOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryRyBaInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback reqWriteJyjlOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryClsslbJyxmOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSynchTimeOperationCompleted;
        
        /// <remarks/>
        public AHOutService() {
            this.Url = "http://192.168.12.10:8088/vehcheckweb/services/OutService.OutServiceHttpSoap11End" +
                "point";
        }

        public AHOutService(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event queryBaInfoCompletedEventHandler queryBaInfoCompleted;
        
        /// <remarks/>
        public event recheckRegisterVehicleOutCompletedEventHandler recheckRegisterVehicleOutCompleted;
        
        /// <remarks/>
        public event queryPcbParaCompletedEventHandler queryPcbParaCompleted;
        
        /// <remarks/>
        public event reqEndCheckProcessOutCompletedEventHandler reqEndCheckProcessOutCompleted;
        
        /// <remarks/>
        public event reqYwtbOutCompletedEventHandler reqYwtbOutCompleted;
        
        /// <remarks/>
        public event queryOutlineSizeCompletedEventHandler queryOutlineSizeCompleted;
        
        /// <remarks/>
        public event reqEndDetectingOutCompletedEventHandler reqEndDetectingOutCompleted;
        
        /// <remarks/>
        public event queryVehicleOutCompletedEventHandler queryVehicleOutCompleted;
        
        /// <remarks/>
        public event reqBeginDetectingOutCompletedEventHandler reqBeginDetectingOutCompleted;
        
        /// <remarks/>
        public event reqCaptureOutCompletedEventHandler reqCaptureOutCompleted;
        
        /// <remarks/>
        public event queryPszpAndJyxmCompletedEventHandler queryPszpAndJyxmCompleted;
        
        /// <remarks/>
        public event registerVehInfoModifyOutCompletedEventHandler registerVehInfoModifyOutCompleted;
        
        /// <remarks/>
        public event reqWriteOtherDataOutCompletedEventHandler reqWriteOtherDataOutCompleted;
        
        /// <remarks/>
        public event queryPcbPhotoCompletedEventHandler queryPcbPhotoCompleted;
        
        /// <remarks/>
        public event reqWriteRgjyxmDataOutCompletedEventHandler reqWriteRgjyxmDataOutCompleted;
        
        /// <remarks/>
        public event queryClWgjyjgCompletedEventHandler queryClWgjyjgCompleted;
        
        /// <remarks/>
        public event registerVehicleOutCompletedEventHandler registerVehicleOutCompleted;
        
        /// <remarks/>
        public event reqWriteCheckDataOutCompletedEventHandler reqWriteCheckDataOutCompleted;
        
        /// <remarks/>
        public event reqBeginCheckProcessOutCompletedEventHandler reqBeginCheckProcessOutCompleted;
        
        /// <remarks/>
        public event reqWriteEnvInspInfoOutCompletedEventHandler reqWriteEnvInspInfoOutCompleted;
        
        /// <remarks/>
        public event queryRyBaInfoCompletedEventHandler queryRyBaInfoCompleted;
        
        /// <remarks/>
        public event reqWriteJyjlOutCompletedEventHandler reqWriteJyjlOutCompleted;
        
        /// <remarks/>
        public event queryClsslbJyxmCompletedEventHandler queryClsslbJyxmCompleted;
        
        /// <remarks/>
        public event getSynchTimeCompletedEventHandler getSynchTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryBaInfo", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryBaInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh) {
            object[] results = this.Invoke("queryBaInfo", new object[] {
                        jkxlh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryBaInfo(string jkxlh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryBaInfo", new object[] {
                        jkxlh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryBaInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryBaInfoAsync(string jkxlh) {
            this.queryBaInfoAsync(jkxlh, null);
        }
        
        /// <remarks/>
        public void queryBaInfoAsync(string jkxlh, object userState) {
            if ((this.queryBaInfoOperationCompleted == null)) {
                this.queryBaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBaInfoOperationCompleted);
            }
            this.InvokeAsync("queryBaInfo", new object[] {
                        jkxlh}, this.queryBaInfoOperationCompleted, userState);
        }
        
        private void OnqueryBaInfoOperationCompleted(object arg) {
            if ((this.queryBaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBaInfoCompleted(this, new queryBaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:recheckRegisterVehicleOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string recheckRegisterVehicleOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string vehXmlDoc) {
            object[] results = this.Invoke("recheckRegisterVehicleOut", new object[] {
                        jkxlh,
                        vehXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginrecheckRegisterVehicleOut(string jkxlh, string vehXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("recheckRegisterVehicleOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndrecheckRegisterVehicleOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void recheckRegisterVehicleOutAsync(string jkxlh, string vehXmlDoc) {
            this.recheckRegisterVehicleOutAsync(jkxlh, vehXmlDoc, null);
        }
        
        /// <remarks/>
        public void recheckRegisterVehicleOutAsync(string jkxlh, string vehXmlDoc, object userState) {
            if ((this.recheckRegisterVehicleOutOperationCompleted == null)) {
                this.recheckRegisterVehicleOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecheckRegisterVehicleOutOperationCompleted);
            }
            this.InvokeAsync("recheckRegisterVehicleOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, this.recheckRegisterVehicleOutOperationCompleted, userState);
        }
        
        private void OnrecheckRegisterVehicleOutOperationCompleted(object arg) {
            if ((this.recheckRegisterVehicleOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recheckRegisterVehicleOutCompleted(this, new recheckRegisterVehicleOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryPcbPara", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryPcbPara([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("queryPcbPara", new object[] {
                        jkxlh,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryPcbPara(string jkxlh, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryPcbPara", new object[] {
                        jkxlh,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryPcbPara(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryPcbParaAsync(string jkxlh, string reqXmlDoc) {
            this.queryPcbParaAsync(jkxlh, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void queryPcbParaAsync(string jkxlh, string reqXmlDoc, object userState) {
            if ((this.queryPcbParaOperationCompleted == null)) {
                this.queryPcbParaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryPcbParaOperationCompleted);
            }
            this.InvokeAsync("queryPcbPara", new object[] {
                        jkxlh,
                        reqXmlDoc}, this.queryPcbParaOperationCompleted, userState);
        }
        
        private void OnqueryPcbParaOperationCompleted(object arg) {
            if ((this.queryPcbParaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryPcbParaCompleted(this, new queryPcbParaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqEndCheckProcessOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqEndCheckProcessOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string regXmlDoc) {
            object[] results = this.Invoke("reqEndCheckProcessOut", new object[] {
                        jkxlh,
                        regXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqEndCheckProcessOut(string jkxlh, string regXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqEndCheckProcessOut", new object[] {
                        jkxlh,
                        regXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqEndCheckProcessOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqEndCheckProcessOutAsync(string jkxlh, string regXmlDoc) {
            this.reqEndCheckProcessOutAsync(jkxlh, regXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqEndCheckProcessOutAsync(string jkxlh, string regXmlDoc, object userState) {
            if ((this.reqEndCheckProcessOutOperationCompleted == null)) {
                this.reqEndCheckProcessOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqEndCheckProcessOutOperationCompleted);
            }
            this.InvokeAsync("reqEndCheckProcessOut", new object[] {
                        jkxlh,
                        regXmlDoc}, this.reqEndCheckProcessOutOperationCompleted, userState);
        }
        
        private void OnreqEndCheckProcessOutOperationCompleted(object arg) {
            if ((this.reqEndCheckProcessOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqEndCheckProcessOutCompleted(this, new reqEndCheckProcessOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqYwtbOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqYwtbOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqYwtbOut", new object[] {
                        jkxlh,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqYwtbOut(string jkxlh, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqYwtbOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqYwtbOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqYwtbOutAsync(string jkxlh, string reqXmlDoc) {
            this.reqYwtbOutAsync(jkxlh, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqYwtbOutAsync(string jkxlh, string reqXmlDoc, object userState) {
            if ((this.reqYwtbOutOperationCompleted == null)) {
                this.reqYwtbOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqYwtbOutOperationCompleted);
            }
            this.InvokeAsync("reqYwtbOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, this.reqYwtbOutOperationCompleted, userState);
        }
        
        private void OnreqYwtbOutOperationCompleted(object arg) {
            if ((this.reqYwtbOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqYwtbOutCompleted(this, new reqYwtbOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryOutlineSize", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryOutlineSize([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jylsh) {
            object[] results = this.Invoke("queryOutlineSize", new object[] {
                        jkxlh,
                        jylsh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryOutlineSize(string jkxlh, string jylsh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryOutlineSize", new object[] {
                        jkxlh,
                        jylsh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryOutlineSize(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryOutlineSizeAsync(string jkxlh, string jylsh) {
            this.queryOutlineSizeAsync(jkxlh, jylsh, null);
        }
        
        /// <remarks/>
        public void queryOutlineSizeAsync(string jkxlh, string jylsh, object userState) {
            if ((this.queryOutlineSizeOperationCompleted == null)) {
                this.queryOutlineSizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOutlineSizeOperationCompleted);
            }
            this.InvokeAsync("queryOutlineSize", new object[] {
                        jkxlh,
                        jylsh}, this.queryOutlineSizeOperationCompleted, userState);
        }
        
        private void OnqueryOutlineSizeOperationCompleted(object arg) {
            if ((this.queryOutlineSizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryOutlineSizeCompleted(this, new queryOutlineSizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqEndDetectingOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqEndDetectingOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqEndDetectingOut", new object[] {
                        jkxlh,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqEndDetectingOut(string jkxlh, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqEndDetectingOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqEndDetectingOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqEndDetectingOutAsync(string jkxlh, string reqXmlDoc) {
            this.reqEndDetectingOutAsync(jkxlh, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqEndDetectingOutAsync(string jkxlh, string reqXmlDoc, object userState) {
            if ((this.reqEndDetectingOutOperationCompleted == null)) {
                this.reqEndDetectingOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqEndDetectingOutOperationCompleted);
            }
            this.InvokeAsync("reqEndDetectingOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, this.reqEndDetectingOutOperationCompleted, userState);
        }
        
        private void OnreqEndDetectingOutOperationCompleted(object arg) {
            if ((this.reqEndDetectingOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqEndDetectingOutCompleted(this, new reqEndDetectingOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryVehicleOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryVehicleOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string hpzl, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string hphm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clsbdh) {
            object[] results = this.Invoke("queryVehicleOut", new object[] {
                        jkxlh,
                        hpzl,
                        hphm,
                        clsbdh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryVehicleOut(string jkxlh, string hpzl, string hphm, string clsbdh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryVehicleOut", new object[] {
                        jkxlh,
                        hpzl,
                        hphm,
                        clsbdh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryVehicleOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryVehicleOutAsync(string jkxlh, string hpzl, string hphm, string clsbdh) {
            this.queryVehicleOutAsync(jkxlh, hpzl, hphm, clsbdh, null);
        }
        
        /// <remarks/>
        public void queryVehicleOutAsync(string jkxlh, string hpzl, string hphm, string clsbdh, object userState) {
            if ((this.queryVehicleOutOperationCompleted == null)) {
                this.queryVehicleOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryVehicleOutOperationCompleted);
            }
            this.InvokeAsync("queryVehicleOut", new object[] {
                        jkxlh,
                        hpzl,
                        hphm,
                        clsbdh}, this.queryVehicleOutOperationCompleted, userState);
        }
        
        private void OnqueryVehicleOutOperationCompleted(object arg) {
            if ((this.queryVehicleOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryVehicleOutCompleted(this, new queryVehicleOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqBeginDetectingOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqBeginDetectingOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string regXmlDoc) {
            object[] results = this.Invoke("reqBeginDetectingOut", new object[] {
                        jkxlh,
                        regXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqBeginDetectingOut(string jkxlh, string regXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqBeginDetectingOut", new object[] {
                        jkxlh,
                        regXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqBeginDetectingOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqBeginDetectingOutAsync(string jkxlh, string regXmlDoc) {
            this.reqBeginDetectingOutAsync(jkxlh, regXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqBeginDetectingOutAsync(string jkxlh, string regXmlDoc, object userState) {
            if ((this.reqBeginDetectingOutOperationCompleted == null)) {
                this.reqBeginDetectingOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqBeginDetectingOutOperationCompleted);
            }
            this.InvokeAsync("reqBeginDetectingOut", new object[] {
                        jkxlh,
                        regXmlDoc}, this.reqBeginDetectingOutOperationCompleted, userState);
        }
        
        private void OnreqBeginDetectingOutOperationCompleted(object arg) {
            if ((this.reqBeginDetectingOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqBeginDetectingOutCompleted(this, new reqBeginDetectingOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqCaptureOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqCaptureOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string vehXmlDoc) {
            object[] results = this.Invoke("reqCaptureOut", new object[] {
                        jkxlh,
                        vehXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqCaptureOut(string jkxlh, string vehXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqCaptureOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqCaptureOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqCaptureOutAsync(string jkxlh, string vehXmlDoc) {
            this.reqCaptureOutAsync(jkxlh, vehXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqCaptureOutAsync(string jkxlh, string vehXmlDoc, object userState) {
            if ((this.reqCaptureOutOperationCompleted == null)) {
                this.reqCaptureOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqCaptureOutOperationCompleted);
            }
            this.InvokeAsync("reqCaptureOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, this.reqCaptureOutOperationCompleted, userState);
        }
        
        private void OnreqCaptureOutOperationCompleted(object arg) {
            if ((this.reqCaptureOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqCaptureOutCompleted(this, new reqCaptureOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryPszpAndJyxm", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryPszpAndJyxm([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string vehXmlDoc) {
            object[] results = this.Invoke("queryPszpAndJyxm", new object[] {
                        jkxlh,
                        vehXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryPszpAndJyxm(string jkxlh, string vehXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryPszpAndJyxm", new object[] {
                        jkxlh,
                        vehXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryPszpAndJyxm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryPszpAndJyxmAsync(string jkxlh, string vehXmlDoc) {
            this.queryPszpAndJyxmAsync(jkxlh, vehXmlDoc, null);
        }
        
        /// <remarks/>
        public void queryPszpAndJyxmAsync(string jkxlh, string vehXmlDoc, object userState) {
            if ((this.queryPszpAndJyxmOperationCompleted == null)) {
                this.queryPszpAndJyxmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryPszpAndJyxmOperationCompleted);
            }
            this.InvokeAsync("queryPszpAndJyxm", new object[] {
                        jkxlh,
                        vehXmlDoc}, this.queryPszpAndJyxmOperationCompleted, userState);
        }
        
        private void OnqueryPszpAndJyxmOperationCompleted(object arg) {
            if ((this.queryPszpAndJyxmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryPszpAndJyxmCompleted(this, new queryPszpAndJyxmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:registerVehInfoModifyOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string registerVehInfoModifyOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string vehXmlDoc) {
            object[] results = this.Invoke("registerVehInfoModifyOut", new object[] {
                        jkxlh,
                        vehXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginregisterVehInfoModifyOut(string jkxlh, string vehXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registerVehInfoModifyOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndregisterVehInfoModifyOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registerVehInfoModifyOutAsync(string jkxlh, string vehXmlDoc) {
            this.registerVehInfoModifyOutAsync(jkxlh, vehXmlDoc, null);
        }
        
        /// <remarks/>
        public void registerVehInfoModifyOutAsync(string jkxlh, string vehXmlDoc, object userState) {
            if ((this.registerVehInfoModifyOutOperationCompleted == null)) {
                this.registerVehInfoModifyOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterVehInfoModifyOutOperationCompleted);
            }
            this.InvokeAsync("registerVehInfoModifyOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, this.registerVehInfoModifyOutOperationCompleted, userState);
        }
        
        private void OnregisterVehInfoModifyOutOperationCompleted(object arg) {
            if ((this.registerVehInfoModifyOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerVehInfoModifyOutCompleted(this, new registerVehInfoModifyOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqWriteOtherDataOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqWriteOtherDataOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqWriteOtherDataOut", new object[] {
                        jkxlh,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqWriteOtherDataOut(string jkxlh, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqWriteOtherDataOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqWriteOtherDataOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqWriteOtherDataOutAsync(string jkxlh, string reqXmlDoc) {
            this.reqWriteOtherDataOutAsync(jkxlh, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqWriteOtherDataOutAsync(string jkxlh, string reqXmlDoc, object userState) {
            if ((this.reqWriteOtherDataOutOperationCompleted == null)) {
                this.reqWriteOtherDataOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqWriteOtherDataOutOperationCompleted);
            }
            this.InvokeAsync("reqWriteOtherDataOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, this.reqWriteOtherDataOutOperationCompleted, userState);
        }
        
        private void OnreqWriteOtherDataOutOperationCompleted(object arg) {
            if ((this.reqWriteOtherDataOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqWriteOtherDataOutCompleted(this, new reqWriteOtherDataOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryPcbPhoto", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryPcbPhoto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string zpbh) {
            object[] results = this.Invoke("queryPcbPhoto", new object[] {
                        jkxlh,
                        zpbh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryPcbPhoto(string jkxlh, string zpbh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryPcbPhoto", new object[] {
                        jkxlh,
                        zpbh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryPcbPhoto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryPcbPhotoAsync(string jkxlh, string zpbh) {
            this.queryPcbPhotoAsync(jkxlh, zpbh, null);
        }
        
        /// <remarks/>
        public void queryPcbPhotoAsync(string jkxlh, string zpbh, object userState) {
            if ((this.queryPcbPhotoOperationCompleted == null)) {
                this.queryPcbPhotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryPcbPhotoOperationCompleted);
            }
            this.InvokeAsync("queryPcbPhoto", new object[] {
                        jkxlh,
                        zpbh}, this.queryPcbPhotoOperationCompleted, userState);
        }
        
        private void OnqueryPcbPhotoOperationCompleted(object arg) {
            if ((this.queryPcbPhotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryPcbPhotoCompleted(this, new queryPcbPhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqWriteRgjyxmDataOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqWriteRgjyxmDataOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jyxm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqWriteRgjyxmDataOut", new object[] {
                        jkxlh,
                        jyxm,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqWriteRgjyxmDataOut(string jkxlh, string jyxm, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqWriteRgjyxmDataOut", new object[] {
                        jkxlh,
                        jyxm,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqWriteRgjyxmDataOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqWriteRgjyxmDataOutAsync(string jkxlh, string jyxm, string reqXmlDoc) {
            this.reqWriteRgjyxmDataOutAsync(jkxlh, jyxm, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqWriteRgjyxmDataOutAsync(string jkxlh, string jyxm, string reqXmlDoc, object userState) {
            if ((this.reqWriteRgjyxmDataOutOperationCompleted == null)) {
                this.reqWriteRgjyxmDataOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqWriteRgjyxmDataOutOperationCompleted);
            }
            this.InvokeAsync("reqWriteRgjyxmDataOut", new object[] {
                        jkxlh,
                        jyxm,
                        reqXmlDoc}, this.reqWriteRgjyxmDataOutOperationCompleted, userState);
        }
        
        private void OnreqWriteRgjyxmDataOutOperationCompleted(object arg) {
            if ((this.reqWriteRgjyxmDataOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqWriteRgjyxmDataOutCompleted(this, new reqWriteRgjyxmDataOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryClWgjyjg", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryClWgjyjg([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jylsh) {
            object[] results = this.Invoke("queryClWgjyjg", new object[] {
                        jkxlh,
                        jylsh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryClWgjyjg(string jkxlh, string jylsh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryClWgjyjg", new object[] {
                        jkxlh,
                        jylsh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryClWgjyjg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryClWgjyjgAsync(string jkxlh, string jylsh) {
            this.queryClWgjyjgAsync(jkxlh, jylsh, null);
        }
        
        /// <remarks/>
        public void queryClWgjyjgAsync(string jkxlh, string jylsh, object userState) {
            if ((this.queryClWgjyjgOperationCompleted == null)) {
                this.queryClWgjyjgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryClWgjyjgOperationCompleted);
            }
            this.InvokeAsync("queryClWgjyjg", new object[] {
                        jkxlh,
                        jylsh}, this.queryClWgjyjgOperationCompleted, userState);
        }
        
        private void OnqueryClWgjyjgOperationCompleted(object arg) {
            if ((this.queryClWgjyjgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryClWgjyjgCompleted(this, new queryClWgjyjgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:registerVehicleOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string registerVehicleOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string vehXmlDoc) {
            object[] results = this.Invoke("registerVehicleOut", new object[] {
                        jkxlh,
                        vehXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginregisterVehicleOut(string jkxlh, string vehXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registerVehicleOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndregisterVehicleOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registerVehicleOutAsync(string jkxlh, string vehXmlDoc) {
            this.registerVehicleOutAsync(jkxlh, vehXmlDoc, null);
        }
        
        /// <remarks/>
        public void registerVehicleOutAsync(string jkxlh, string vehXmlDoc, object userState) {
            if ((this.registerVehicleOutOperationCompleted == null)) {
                this.registerVehicleOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterVehicleOutOperationCompleted);
            }
            this.InvokeAsync("registerVehicleOut", new object[] {
                        jkxlh,
                        vehXmlDoc}, this.registerVehicleOutOperationCompleted, userState);
        }
        
        private void OnregisterVehicleOutOperationCompleted(object arg) {
            if ((this.registerVehicleOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerVehicleOutCompleted(this, new registerVehicleOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqWriteCheckDataOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqWriteCheckDataOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jyxm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqWriteCheckDataOut", new object[] {
                        jkxlh,
                        jyxm,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqWriteCheckDataOut(string jkxlh, string jyxm, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqWriteCheckDataOut", new object[] {
                        jkxlh,
                        jyxm,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqWriteCheckDataOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqWriteCheckDataOutAsync(string jkxlh, string jyxm, string reqXmlDoc) {
            this.reqWriteCheckDataOutAsync(jkxlh, jyxm, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqWriteCheckDataOutAsync(string jkxlh, string jyxm, string reqXmlDoc, object userState) {
            if ((this.reqWriteCheckDataOutOperationCompleted == null)) {
                this.reqWriteCheckDataOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqWriteCheckDataOutOperationCompleted);
            }
            this.InvokeAsync("reqWriteCheckDataOut", new object[] {
                        jkxlh,
                        jyxm,
                        reqXmlDoc}, this.reqWriteCheckDataOutOperationCompleted, userState);
        }
        
        private void OnreqWriteCheckDataOutOperationCompleted(object arg) {
            if ((this.reqWriteCheckDataOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqWriteCheckDataOutCompleted(this, new reqWriteCheckDataOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqBeginCheckProcessOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqBeginCheckProcessOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string regXmlDoc) {
            object[] results = this.Invoke("reqBeginCheckProcessOut", new object[] {
                        jkxlh,
                        regXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqBeginCheckProcessOut(string jkxlh, string regXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqBeginCheckProcessOut", new object[] {
                        jkxlh,
                        regXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqBeginCheckProcessOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqBeginCheckProcessOutAsync(string jkxlh, string regXmlDoc) {
            this.reqBeginCheckProcessOutAsync(jkxlh, regXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqBeginCheckProcessOutAsync(string jkxlh, string regXmlDoc, object userState) {
            if ((this.reqBeginCheckProcessOutOperationCompleted == null)) {
                this.reqBeginCheckProcessOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqBeginCheckProcessOutOperationCompleted);
            }
            this.InvokeAsync("reqBeginCheckProcessOut", new object[] {
                        jkxlh,
                        regXmlDoc}, this.reqBeginCheckProcessOutOperationCompleted, userState);
        }
        
        private void OnreqBeginCheckProcessOutOperationCompleted(object arg) {
            if ((this.reqBeginCheckProcessOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqBeginCheckProcessOutCompleted(this, new reqBeginCheckProcessOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqWriteEnvInspInfoOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqWriteEnvInspInfoOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqWriteEnvInspInfoOut", new object[] {
                        jkxlh,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqWriteEnvInspInfoOut(string jkxlh, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqWriteEnvInspInfoOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqWriteEnvInspInfoOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqWriteEnvInspInfoOutAsync(string jkxlh, string reqXmlDoc) {
            this.reqWriteEnvInspInfoOutAsync(jkxlh, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqWriteEnvInspInfoOutAsync(string jkxlh, string reqXmlDoc, object userState) {
            if ((this.reqWriteEnvInspInfoOutOperationCompleted == null)) {
                this.reqWriteEnvInspInfoOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqWriteEnvInspInfoOutOperationCompleted);
            }
            this.InvokeAsync("reqWriteEnvInspInfoOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, this.reqWriteEnvInspInfoOutOperationCompleted, userState);
        }
        
        private void OnreqWriteEnvInspInfoOutOperationCompleted(object arg) {
            if ((this.reqWriteEnvInspInfoOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqWriteEnvInspInfoOutCompleted(this, new reqWriteEnvInspInfoOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryRyBaInfo", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryRyBaInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sfzmhm, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xm) {
            object[] results = this.Invoke("queryRyBaInfo", new object[] {
                        jkxlh,
                        sfzmhm,
                        xm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryRyBaInfo(string jkxlh, string sfzmhm, string xm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryRyBaInfo", new object[] {
                        jkxlh,
                        sfzmhm,
                        xm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryRyBaInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryRyBaInfoAsync(string jkxlh, string sfzmhm, string xm) {
            this.queryRyBaInfoAsync(jkxlh, sfzmhm, xm, null);
        }
        
        /// <remarks/>
        public void queryRyBaInfoAsync(string jkxlh, string sfzmhm, string xm, object userState) {
            if ((this.queryRyBaInfoOperationCompleted == null)) {
                this.queryRyBaInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryRyBaInfoOperationCompleted);
            }
            this.InvokeAsync("queryRyBaInfo", new object[] {
                        jkxlh,
                        sfzmhm,
                        xm}, this.queryRyBaInfoOperationCompleted, userState);
        }
        
        private void OnqueryRyBaInfoOperationCompleted(object arg) {
            if ((this.queryRyBaInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryRyBaInfoCompleted(this, new queryRyBaInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:reqWriteJyjlOut", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string reqWriteJyjlOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reqXmlDoc) {
            object[] results = this.Invoke("reqWriteJyjlOut", new object[] {
                        jkxlh,
                        reqXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreqWriteJyjlOut(string jkxlh, string reqXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("reqWriteJyjlOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndreqWriteJyjlOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reqWriteJyjlOutAsync(string jkxlh, string reqXmlDoc) {
            this.reqWriteJyjlOutAsync(jkxlh, reqXmlDoc, null);
        }
        
        /// <remarks/>
        public void reqWriteJyjlOutAsync(string jkxlh, string reqXmlDoc, object userState) {
            if ((this.reqWriteJyjlOutOperationCompleted == null)) {
                this.reqWriteJyjlOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreqWriteJyjlOutOperationCompleted);
            }
            this.InvokeAsync("reqWriteJyjlOut", new object[] {
                        jkxlh,
                        reqXmlDoc}, this.reqWriteJyjlOutOperationCompleted, userState);
        }
        
        private void OnreqWriteJyjlOutOperationCompleted(object arg) {
            if ((this.reqWriteJyjlOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reqWriteJyjlOutCompleted(this, new reqWriteJyjlOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:queryClsslbJyxm", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string queryClsslbJyxm([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jylb) {
            object[] results = this.Invoke("queryClsslbJyxm", new object[] {
                        jkxlh,
                        jylb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryClsslbJyxm(string jkxlh, string jylb, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryClsslbJyxm", new object[] {
                        jkxlh,
                        jylb}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryClsslbJyxm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryClsslbJyxmAsync(string jkxlh, string jylb) {
            this.queryClsslbJyxmAsync(jkxlh, jylb, null);
        }
        
        /// <remarks/>
        public void queryClsslbJyxmAsync(string jkxlh, string jylb, object userState) {
            if ((this.queryClsslbJyxmOperationCompleted == null)) {
                this.queryClsslbJyxmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryClsslbJyxmOperationCompleted);
            }
            this.InvokeAsync("queryClsslbJyxm", new object[] {
                        jkxlh,
                        jylb}, this.queryClsslbJyxmOperationCompleted, userState);
        }
        
        private void OnqueryClsslbJyxmOperationCompleted(object arg) {
            if ((this.queryClsslbJyxmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryClsslbJyxmCompleted(this, new queryClsslbJyxmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getSynchTime", RequestNamespace="http://outservice.checkinspect.ahkeli.com", ResponseNamespace="http://outservice.checkinspect.ahkeli.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getSynchTime([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string jkxlh) {
            object[] results = this.Invoke("getSynchTime", new object[] {
                        jkxlh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSynchTime(string jkxlh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSynchTime", new object[] {
                        jkxlh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetSynchTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSynchTimeAsync(string jkxlh) {
            this.getSynchTimeAsync(jkxlh, null);
        }
        
        /// <remarks/>
        public void getSynchTimeAsync(string jkxlh, object userState) {
            if ((this.getSynchTimeOperationCompleted == null)) {
                this.getSynchTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSynchTimeOperationCompleted);
            }
            this.InvokeAsync("getSynchTime", new object[] {
                        jkxlh}, this.getSynchTimeOperationCompleted, userState);
        }
        
        private void OngetSynchTimeOperationCompleted(object arg) {
            if ((this.getSynchTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSynchTimeCompleted(this, new getSynchTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryBaInfoCompletedEventHandler(object sender, queryBaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryBaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void recheckRegisterVehicleOutCompletedEventHandler(object sender, recheckRegisterVehicleOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recheckRegisterVehicleOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recheckRegisterVehicleOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryPcbParaCompletedEventHandler(object sender, queryPcbParaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryPcbParaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryPcbParaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqEndCheckProcessOutCompletedEventHandler(object sender, reqEndCheckProcessOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqEndCheckProcessOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqEndCheckProcessOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqYwtbOutCompletedEventHandler(object sender, reqYwtbOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqYwtbOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqYwtbOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryOutlineSizeCompletedEventHandler(object sender, queryOutlineSizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryOutlineSizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryOutlineSizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqEndDetectingOutCompletedEventHandler(object sender, reqEndDetectingOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqEndDetectingOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqEndDetectingOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryVehicleOutCompletedEventHandler(object sender, queryVehicleOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryVehicleOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryVehicleOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqBeginDetectingOutCompletedEventHandler(object sender, reqBeginDetectingOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqBeginDetectingOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqBeginDetectingOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqCaptureOutCompletedEventHandler(object sender, reqCaptureOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqCaptureOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqCaptureOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryPszpAndJyxmCompletedEventHandler(object sender, queryPszpAndJyxmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryPszpAndJyxmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryPszpAndJyxmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void registerVehInfoModifyOutCompletedEventHandler(object sender, registerVehInfoModifyOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerVehInfoModifyOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registerVehInfoModifyOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqWriteOtherDataOutCompletedEventHandler(object sender, reqWriteOtherDataOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqWriteOtherDataOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqWriteOtherDataOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryPcbPhotoCompletedEventHandler(object sender, queryPcbPhotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryPcbPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryPcbPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqWriteRgjyxmDataOutCompletedEventHandler(object sender, reqWriteRgjyxmDataOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqWriteRgjyxmDataOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqWriteRgjyxmDataOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryClWgjyjgCompletedEventHandler(object sender, queryClWgjyjgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryClWgjyjgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryClWgjyjgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void registerVehicleOutCompletedEventHandler(object sender, registerVehicleOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registerVehicleOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registerVehicleOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqWriteCheckDataOutCompletedEventHandler(object sender, reqWriteCheckDataOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqWriteCheckDataOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqWriteCheckDataOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqBeginCheckProcessOutCompletedEventHandler(object sender, reqBeginCheckProcessOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqBeginCheckProcessOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqBeginCheckProcessOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqWriteEnvInspInfoOutCompletedEventHandler(object sender, reqWriteEnvInspInfoOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqWriteEnvInspInfoOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqWriteEnvInspInfoOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryRyBaInfoCompletedEventHandler(object sender, queryRyBaInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryRyBaInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryRyBaInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void reqWriteJyjlOutCompletedEventHandler(object sender, reqWriteJyjlOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reqWriteJyjlOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reqWriteJyjlOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void queryClsslbJyxmCompletedEventHandler(object sender, queryClsslbJyxmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryClsslbJyxmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryClsslbJyxmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getSynchTimeCompletedEventHandler(object sender, getSynchTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSynchTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSynchTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
