//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace NetSendWaitCar {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BHService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryObjectOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback writeObjectOutOperationCompleted;
        
        /// <remarks/>
        public BHService() {
            this.Url = "http://192.168.1.151/VehWGJK/service.asmx";
        }

        public BHService(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event BHqueryObjectOutCompletedEventHandler queryObjectOutCompleted;
        
        /// <remarks/>
        public event BHwriteObjectOutCompletedEventHandler writeObjectOutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryObjectOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnInfo queryObjectOut(string jkxlh, string jkid, string QueryXmlDoc) {
            IOControl.saveXmlLogInf("queryObjectOut|jkxlh:" + jkxlh + "|jkid:" + jkid + "\r\nQueryXmlDoc:" + QueryXmlDoc + "\r\n");
            object[] results = this.Invoke("queryObjectOut", new object[] {
                        jkxlh,
                        jkid,
                        QueryXmlDoc});
            return ((ReturnInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryObjectOut(string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryObjectOut", new object[] {
                        jkxlh,
                        jkid,
                        QueryXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReturnInfo EndqueryObjectOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnInfo)(results[0]));
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string jkxlh, string jkid, string QueryXmlDoc) {
            this.queryObjectOutAsync(jkxlh, jkid, QueryXmlDoc, null);
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string jkxlh, string jkid, string QueryXmlDoc, object userState) {
            if ((this.queryObjectOutOperationCompleted == null)) {
                this.queryObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryObjectOutOperationCompleted);
            }
            this.InvokeAsync("queryObjectOut", new object[] {
                        jkxlh,
                        jkid,
                        QueryXmlDoc}, this.queryObjectOutOperationCompleted, userState);
        }
        
        private void OnqueryObjectOutOperationCompleted(object arg) {
            if ((this.queryObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryObjectOutCompleted(this, new BHqueryObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/writeObjectOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnInfo writeObjectOut(string jkxlh, string jkid, string WriteXmlDoc) {
            IOControl.saveXmlLogInf("writeObjectOut|jkxlh:" + jkxlh + "|jkid:" + jkid + "\r\nWriteXmlDoc:" + WriteXmlDoc + "\r\n");
            object[] results = this.Invoke("writeObjectOut", new object[] {
                        jkxlh,
                        jkid,
                        WriteXmlDoc});
            return ((ReturnInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwriteObjectOut(string jkxlh, string jkid, string WriteXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("writeObjectOut", new object[] {
                        jkxlh,
                        jkid,
                        WriteXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReturnInfo EndwriteObjectOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnInfo)(results[0]));
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string jkxlh, string jkid, string WriteXmlDoc) {
            this.writeObjectOutAsync(jkxlh, jkid, WriteXmlDoc, null);
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string jkxlh, string jkid, string WriteXmlDoc, object userState) {
            if ((this.writeObjectOutOperationCompleted == null)) {
                this.writeObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteObjectOutOperationCompleted);
            }
            this.InvokeAsync("writeObjectOut", new object[] {
                        jkxlh,
                        jkid,
                        WriteXmlDoc}, this.writeObjectOutOperationCompleted, userState);
        }
        
        private void OnwriteObjectOutOperationCompleted(object arg) {
            if ((this.writeObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.writeObjectOutCompleted(this, new BHwriteObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnInfo {
        
        private int codeField;
        
        private string messageField;
        
        private int rownumField;
        
        private System.Data.DataTable infoField;
        
        private string infoXMLField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int rownum {
            get {
                return this.rownumField;
            }
            set {
                this.rownumField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        public string infoXML {
            get {
                return this.infoXMLField;
            }
            set {
                this.infoXMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void BHqueryObjectOutCompletedEventHandler(object sender, BHqueryObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BHqueryObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BHqueryObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void BHwriteObjectOutCompletedEventHandler(object sender, BHwriteObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BHwriteObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BHwriteObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnInfo)(this.results[0]));
            }
        }
    }
}
