//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace NetSendWaitCar {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CarTestHandleService1Soap", Namespace="http://www.hyjtkj.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class HYCarTestHandleService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryObjectOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback writeObjectOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteSqlCommandOperationCompleted;
        
        private System.Threading.SendOrPostCallback MergeDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataServiceOperationCompleted;
        
        /// <remarks/>
        public HYCarTestHandleService1() {
            this.Url = "http://172.23.25.95:8086/CarTestHandleService.asmx";
        }

        public HYCarTestHandleService1(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event GetVersionCompletedEventHandler GetVersionCompleted;
        
        /// <remarks/>
        public event HYqueryObjectOutCompletedEventHandler queryObjectOutCompleted;
        
        /// <remarks/>
        public event HYwriteObjectOutCompletedEventHandler writeObjectOutCompleted;
        
        /// <remarks/>
        public event ExecuteSqlCommandCompletedEventHandler ExecuteSqlCommandCompleted;
        
        /// <remarks/>
        public event MergeDataCompletedEventHandler MergeDataCompleted;
        
        /// <remarks/>
        public event dataServiceCompletedEventHandler dataServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hyjtkj.com/GetVersion", RequestNamespace="http://www.hyjtkj.com/", ResponseNamespace="http://www.hyjtkj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVersion() {
            object[] results = this.Invoke("GetVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVersionAsync() {
            this.GetVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetVersionAsync(object userState) {
            if ((this.GetVersionOperationCompleted == null)) {
                this.GetVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersionOperationCompleted);
            }
            this.InvokeAsync("GetVersion", new object[0], this.GetVersionOperationCompleted, userState);
        }
        
        private void OnGetVersionOperationCompleted(object arg) {
            if ((this.GetVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersionCompleted(this, new GetVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hyjtkj.com/queryObjectOut", RequestNamespace="http://www.hyjtkj.com/", ResponseNamespace="http://www.hyjtkj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryObjectOut(string xtlb, string jkxlh, string jkid, string QueryUTF8XmlDoc) {
            object[] results = this.Invoke("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryUTF8XmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryObjectOut(string xtlb, string jkxlh, string jkid, string QueryUTF8XmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryUTF8XmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryObjectOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryUTF8XmlDoc) {
            this.queryObjectOutAsync(xtlb, jkxlh, jkid, QueryUTF8XmlDoc, null);
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryUTF8XmlDoc, object userState) {
            if ((this.queryObjectOutOperationCompleted == null)) {
                this.queryObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryObjectOutOperationCompleted);
            }
            this.InvokeAsync("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryUTF8XmlDoc}, this.queryObjectOutOperationCompleted, userState);
        }
        
        private void OnqueryObjectOutOperationCompleted(object arg) {
            if ((this.queryObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryObjectOutCompleted(this, new HYqueryObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hyjtkj.com/writeObjectOut", RequestNamespace="http://www.hyjtkj.com/", ResponseNamespace="http://www.hyjtkj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string writeObjectOut(string xtlb, string jkxlh, string jkid, string writeUTF8XmlDoc) {
            object[] results = this.Invoke("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        writeUTF8XmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwriteObjectOut(string xtlb, string jkxlh, string jkid, string writeUTF8XmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        writeUTF8XmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwriteObjectOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string writeUTF8XmlDoc) {
            this.writeObjectOutAsync(xtlb, jkxlh, jkid, writeUTF8XmlDoc, null);
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string writeUTF8XmlDoc, object userState) {
            if ((this.writeObjectOutOperationCompleted == null)) {
                this.writeObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteObjectOutOperationCompleted);
            }
            this.InvokeAsync("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        writeUTF8XmlDoc}, this.writeObjectOutOperationCompleted, userState);
        }
        
        private void OnwriteObjectOutOperationCompleted(object arg) {
            if ((this.writeObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.writeObjectOutCompleted(this, new HYwriteObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hyjtkj.com/ExecuteSqlCommand", RequestNamespace="http://www.hyjtkj.com/", ResponseNamespace="http://www.hyjtkj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecuteSqlCommand(string xtlb, string jkxlh, string cmdText, object[] parameters) {
            object[] results = this.Invoke("ExecuteSqlCommand", new object[] {
                        xtlb,
                        jkxlh,
                        cmdText,
                        parameters});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecuteSqlCommand(string xtlb, string jkxlh, string cmdText, object[] parameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExecuteSqlCommand", new object[] {
                        xtlb,
                        jkxlh,
                        cmdText,
                        parameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndExecuteSqlCommand(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteSqlCommandAsync(string xtlb, string jkxlh, string cmdText, object[] parameters) {
            this.ExecuteSqlCommandAsync(xtlb, jkxlh, cmdText, parameters, null);
        }
        
        /// <remarks/>
        public void ExecuteSqlCommandAsync(string xtlb, string jkxlh, string cmdText, object[] parameters, object userState) {
            if ((this.ExecuteSqlCommandOperationCompleted == null)) {
                this.ExecuteSqlCommandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteSqlCommandOperationCompleted);
            }
            this.InvokeAsync("ExecuteSqlCommand", new object[] {
                        xtlb,
                        jkxlh,
                        cmdText,
                        parameters}, this.ExecuteSqlCommandOperationCompleted, userState);
        }
        
        private void OnExecuteSqlCommandOperationCompleted(object arg) {
            if ((this.ExecuteSqlCommandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteSqlCommandCompleted(this, new ExecuteSqlCommandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hyjtkj.com/MergeData", RequestNamespace="http://www.hyjtkj.com/", ResponseNamespace="http://www.hyjtkj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MergeData(string jylsh, string jycs, string outSideItem, bool forceMerge) {
            object[] results = this.Invoke("MergeData", new object[] {
                        jylsh,
                        jycs,
                        outSideItem,
                        forceMerge});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMergeData(string jylsh, string jycs, string outSideItem, bool forceMerge, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MergeData", new object[] {
                        jylsh,
                        jycs,
                        outSideItem,
                        forceMerge}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndMergeData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MergeDataAsync(string jylsh, string jycs, string outSideItem, bool forceMerge) {
            this.MergeDataAsync(jylsh, jycs, outSideItem, forceMerge, null);
        }
        
        /// <remarks/>
        public void MergeDataAsync(string jylsh, string jycs, string outSideItem, bool forceMerge, object userState) {
            if ((this.MergeDataOperationCompleted == null)) {
                this.MergeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMergeDataOperationCompleted);
            }
            this.InvokeAsync("MergeData", new object[] {
                        jylsh,
                        jycs,
                        outSideItem,
                        forceMerge}, this.MergeDataOperationCompleted, userState);
        }
        
        private void OnMergeDataOperationCompleted(object arg) {
            if ((this.MergeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MergeDataCompleted(this, new MergeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hyjtkj.com/dataService", RequestNamespace="http://www.hyjtkj.com/", ResponseNamespace="http://www.hyjtkj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dataService(string verification, string type, string data) {
            object[] results = this.Invoke("dataService", new object[] {
                        verification,
                        type,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindataService(string verification, string type, string data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dataService", new object[] {
                        verification,
                        type,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddataService(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dataServiceAsync(string verification, string type, string data) {
            this.dataServiceAsync(verification, type, data, null);
        }
        
        /// <remarks/>
        public void dataServiceAsync(string verification, string type, string data, object userState) {
            if ((this.dataServiceOperationCompleted == null)) {
                this.dataServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataServiceOperationCompleted);
            }
            this.InvokeAsync("dataService", new object[] {
                        verification,
                        type,
                        data}, this.dataServiceOperationCompleted, userState);
        }
        
        private void OndataServiceOperationCompleted(object arg) {
            if ((this.dataServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataServiceCompleted(this, new dataServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void GetVersionCompletedEventHandler(object sender, GetVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void HYqueryObjectOutCompletedEventHandler(object sender, HYqueryObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HYqueryObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HYqueryObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void HYwriteObjectOutCompletedEventHandler(object sender, HYwriteObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HYwriteObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HYwriteObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ExecuteSqlCommandCompletedEventHandler(object sender, ExecuteSqlCommandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteSqlCommandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteSqlCommandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void MergeDataCompletedEventHandler(object sender, MergeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MergeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MergeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void dataServiceCompletedEventHandler(object sender, dataServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
