//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;


// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TmriOutAccessSoap", Namespace="http://localhost:1044/")]
public partial class xdTmriOutAccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback writeObjectOutOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryObjectOutOperationCompleted;
    
    private System.Threading.SendOrPostCallback URLEncodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback URLDecodeOperationCompleted;
    
    /// <remarks/>
    public xdTmriOutAccess() {
        this.Url = "http://192.10.10.200/TrffWeb/JCZService/TmriOutAccess.asmx";
    }

    public xdTmriOutAccess(string url)
    {
        this.Url = url;
    }
    /// <remarks/>
    public event XDwriteObjectOutCompletedEventHandler writeObjectOutCompleted;
    
    /// <remarks/>
    public event XDqueryObjectOutCompletedEventHandler queryObjectOutCompleted;
    
    /// <remarks/>
    public event URLEncodeCompletedEventHandler URLEncodeCompleted;
    
    /// <remarks/>
    public event URLDecodeCompletedEventHandler URLDecodeCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:1044/writeObjectOut", RequestNamespace="http://localhost:1044/", ResponseNamespace="http://localhost:1044/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string writeObjectOut(string xtlb, string jkxlh, string jkid, string xmlDoc) {
        object[] results = this.Invoke("writeObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    xmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginwriteObjectOut(string xtlb, string jkxlh, string jkid, string xmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("writeObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    xmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndwriteObjectOut(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string xmlDoc) {
        this.writeObjectOutAsync(xtlb, jkxlh, jkid, xmlDoc, null);
    }
    
    /// <remarks/>
    public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string xmlDoc, object userState) {
        if ((this.writeObjectOutOperationCompleted == null)) {
            this.writeObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteObjectOutOperationCompleted);
        }
        this.InvokeAsync("writeObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    xmlDoc}, this.writeObjectOutOperationCompleted, userState);
    }
    
    private void OnwriteObjectOutOperationCompleted(object arg) {
        if ((this.writeObjectOutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.writeObjectOutCompleted(this, new XDwriteObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:1044/queryObjectOut", RequestNamespace="http://localhost:1044/", ResponseNamespace="http://localhost:1044/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string queryObjectOut(string xtlb, string jkxlh, string jkid, string xmlDoc) {
        object[] results = this.Invoke("queryObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    xmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryObjectOut(string xtlb, string jkxlh, string jkid, string xmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    xmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndqueryObjectOut(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string xmlDoc) {
        this.queryObjectOutAsync(xtlb, jkxlh, jkid, xmlDoc, null);
    }
    
    /// <remarks/>
    public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string xmlDoc, object userState) {
        if ((this.queryObjectOutOperationCompleted == null)) {
            this.queryObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryObjectOutOperationCompleted);
        }
        this.InvokeAsync("queryObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    xmlDoc}, this.queryObjectOutOperationCompleted, userState);
    }
    
    private void OnqueryObjectOutOperationCompleted(object arg) {
        if ((this.queryObjectOutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryObjectOutCompleted(this, new XDqueryObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:1044/URLEncode", RequestNamespace="http://localhost:1044/", ResponseNamespace="http://localhost:1044/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string URLEncode(string xtlb, string jkxlh, string data) {
        object[] results = this.Invoke("URLEncode", new object[] {
                    xtlb,
                    jkxlh,
                    data});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginURLEncode(string xtlb, string jkxlh, string data, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("URLEncode", new object[] {
                    xtlb,
                    jkxlh,
                    data}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndURLEncode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void URLEncodeAsync(string xtlb, string jkxlh, string data) {
        this.URLEncodeAsync(xtlb, jkxlh, data, null);
    }
    
    /// <remarks/>
    public void URLEncodeAsync(string xtlb, string jkxlh, string data, object userState) {
        if ((this.URLEncodeOperationCompleted == null)) {
            this.URLEncodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnURLEncodeOperationCompleted);
        }
        this.InvokeAsync("URLEncode", new object[] {
                    xtlb,
                    jkxlh,
                    data}, this.URLEncodeOperationCompleted, userState);
    }
    
    private void OnURLEncodeOperationCompleted(object arg) {
        if ((this.URLEncodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.URLEncodeCompleted(this, new URLEncodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:1044/URLDecode", RequestNamespace="http://localhost:1044/", ResponseNamespace="http://localhost:1044/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string URLDecode(string xtlb, string jkxlh, string data) {
        object[] results = this.Invoke("URLDecode", new object[] {
                    xtlb,
                    jkxlh,
                    data});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginURLDecode(string xtlb, string jkxlh, string data, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("URLDecode", new object[] {
                    xtlb,
                    jkxlh,
                    data}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndURLDecode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void URLDecodeAsync(string xtlb, string jkxlh, string data) {
        this.URLDecodeAsync(xtlb, jkxlh, data, null);
    }
    
    /// <remarks/>
    public void URLDecodeAsync(string xtlb, string jkxlh, string data, object userState) {
        if ((this.URLDecodeOperationCompleted == null)) {
            this.URLDecodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnURLDecodeOperationCompleted);
        }
        this.InvokeAsync("URLDecode", new object[] {
                    xtlb,
                    jkxlh,
                    data}, this.URLDecodeOperationCompleted, userState);
    }
    
    private void OnURLDecodeOperationCompleted(object arg) {
        if ((this.URLDecodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.URLDecodeCompleted(this, new URLDecodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void XDwriteObjectOutCompletedEventHandler(object sender, XDwriteObjectOutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XDwriteObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal XDwriteObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void XDqueryObjectOutCompletedEventHandler(object sender, XDqueryObjectOutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XDqueryObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal XDqueryObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void URLEncodeCompletedEventHandler(object sender, URLEncodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class URLEncodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal URLEncodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void URLDecodeCompletedEventHandler(object sender, URLDecodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class URLDecodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal URLDecodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
