//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace LwhUploadOnline {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="jcjkServiceSoapBinding", Namespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
    public partial class HBCarryJcjkServicesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback writeObjectOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXydcInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryObjectOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback updpassOperationCompleted;
        
        private System.Threading.SendOrPostCallback getZdxxOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWjtdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getZpgwcsOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadWjzpOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWjzpOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBbhOperationCompleted;
        
        private System.Threading.SendOrPostCallback downLoadChunkOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJcxWjyhlbOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPdabaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJczInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSerTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback encodeUTF8OperationCompleted;
        
        private System.Threading.SendOrPostCallback getSpsbxxOperationCompleted;
        
        private System.Threading.SendOrPostCallback isJkxlhOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXydcListOperationCompleted;
        
        private System.Threading.SendOrPostCallback endXydcZjOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadXydcZjOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkXmEndOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadFileEndOperationCompleted;
        
        /// <remarks/>
        public HBCarryJcjkServicesService() {
            this.Url = "http://192.168.31.126:9080/jcjklw/services/jcjkService";
        }
        public HBCarryJcjkServicesService(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event HBwriteObjectOutCompletedEventHandler writeObjectOutCompleted;
        
        /// <remarks/>
        public event getXydcInfoCompletedEventHandler getXydcInfoCompleted;
        
        /// <remarks/>
        public event HBqueryObjectOutCompletedEventHandler queryObjectOutCompleted;
        
        /// <remarks/>
        public event checkUserCompletedEventHandler checkUserCompleted;
        
        /// <remarks/>
        public event updpassCompletedEventHandler updpassCompleted;
        
        /// <remarks/>
        public event getZdxxCompletedEventHandler getZdxxCompleted;
        
        /// <remarks/>
        public event getWjtdCompletedEventHandler getWjtdCompleted;
        
        /// <remarks/>
        public event getZpgwcsCompletedEventHandler getZpgwcsCompleted;
        
        /// <remarks/>
        public event uploadWjzpCompletedEventHandler uploadWjzpCompleted;
        
        /// <remarks/>
        public event getWjzpCompletedEventHandler getWjzpCompleted;
        
        /// <remarks/>
        public event getBbhCompletedEventHandler getBbhCompleted;
        
        /// <remarks/>
        public event downLoadChunkCompletedEventHandler downLoadChunkCompleted;
        
        /// <remarks/>
        public event getJcxWjyhlbCompletedEventHandler getJcxWjyhlbCompleted;
        
        /// <remarks/>
        public event setPdabaCompletedEventHandler setPdabaCompleted;
        
        /// <remarks/>
        public event getJczInfoCompletedEventHandler getJczInfoCompleted;
        
        /// <remarks/>
        public event getSerTimeCompletedEventHandler getSerTimeCompleted;
        
        /// <remarks/>
        public event encodeUTF8CompletedEventHandler encodeUTF8Completed;
        
        /// <remarks/>
        public event getSpsbxxCompletedEventHandler getSpsbxxCompleted;
        
        /// <remarks/>
        public event isJkxlhCompletedEventHandler isJkxlhCompleted;
        
        /// <remarks/>
        public event getXydcListCompletedEventHandler getXydcListCompleted;
        
        /// <remarks/>
        public event endXydcZjCompletedEventHandler endXydcZjCompleted;
        
        /// <remarks/>
        public event uploadXydcZjCompletedEventHandler uploadXydcZjCompleted;
        
        /// <remarks/>
        public event checkXmEndCompletedEventHandler checkXmEndCompleted;
        
        /// <remarks/>
        public event uploadFileCompletedEventHandler uploadFileCompleted;
        
        /// <remarks/>
        public event uploadFileEndCompletedEventHandler uploadFileEndCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("writeObjectOutReturn")]
        public string writeObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
            object[] results = this.Invoke("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwriteObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwriteObjectOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
            this.writeObjectOutAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
        }
        
        /// <remarks/>
        public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
            if ((this.writeObjectOutOperationCompleted == null)) {
                this.writeObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteObjectOutOperationCompleted);
            }
            this.InvokeAsync("writeObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryXmlDoc}, this.writeObjectOutOperationCompleted, userState);
        }
        
        private void OnwriteObjectOutOperationCompleted(object arg) {
            if ((this.writeObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.writeObjectOutCompleted(this, new HBwriteObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getXydcInfoReturn")]
        public string getXydcInfo(string jyjgbh, string jylsh, string xyzl, string jkxlh) {
            object[] results = this.Invoke("getXydcInfo", new object[] {
                        jyjgbh,
                        jylsh,
                        xyzl,
                        jkxlh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetXydcInfo(string jyjgbh, string jylsh, string xyzl, string jkxlh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getXydcInfo", new object[] {
                        jyjgbh,
                        jylsh,
                        xyzl,
                        jkxlh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetXydcInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXydcInfoAsync(string jyjgbh, string jylsh, string xyzl, string jkxlh) {
            this.getXydcInfoAsync(jyjgbh, jylsh, xyzl, jkxlh, null);
        }
        
        /// <remarks/>
        public void getXydcInfoAsync(string jyjgbh, string jylsh, string xyzl, string jkxlh, object userState) {
            if ((this.getXydcInfoOperationCompleted == null)) {
                this.getXydcInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXydcInfoOperationCompleted);
            }
            this.InvokeAsync("getXydcInfo", new object[] {
                        jyjgbh,
                        jylsh,
                        xyzl,
                        jkxlh}, this.getXydcInfoOperationCompleted, userState);
        }
        
        private void OngetXydcInfoOperationCompleted(object arg) {
            if ((this.getXydcInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXydcInfoCompleted(this, new getXydcInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("queryObjectOutReturn")]
        public string queryObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
            object[] results = this.Invoke("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryObjectOut(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
            this.queryObjectOutAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
        }
        
        /// <remarks/>
        public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
            if ((this.queryObjectOutOperationCompleted == null)) {
                this.queryObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryObjectOutOperationCompleted);
            }
            this.InvokeAsync("queryObjectOut", new object[] {
                        xtlb,
                        jkxlh,
                        jkid,
                        QueryXmlDoc}, this.queryObjectOutOperationCompleted, userState);
        }
        
        private void OnqueryObjectOutOperationCompleted(object arg) {
            if ((this.queryObjectOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryObjectOutCompleted(this, new HBqueryObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkUserReturn")]
        public string checkUser(string bbh, string dlmc, string password, string jyjgbh, string pdaid) {
            object[] results = this.Invoke("checkUser", new object[] {
                        bbh,
                        dlmc,
                        password,
                        jyjgbh,
                        pdaid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckUser(string bbh, string dlmc, string password, string jyjgbh, string pdaid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkUser", new object[] {
                        bbh,
                        dlmc,
                        password,
                        jyjgbh,
                        pdaid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkUserAsync(string bbh, string dlmc, string password, string jyjgbh, string pdaid) {
            this.checkUserAsync(bbh, dlmc, password, jyjgbh, pdaid, null);
        }
        
        /// <remarks/>
        public void checkUserAsync(string bbh, string dlmc, string password, string jyjgbh, string pdaid, object userState) {
            if ((this.checkUserOperationCompleted == null)) {
                this.checkUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckUserOperationCompleted);
            }
            this.InvokeAsync("checkUser", new object[] {
                        bbh,
                        dlmc,
                        password,
                        jyjgbh,
                        pdaid}, this.checkUserOperationCompleted, userState);
        }
        
        private void OncheckUserOperationCompleted(object arg) {
            if ((this.checkUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkUserCompleted(this, new checkUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("updpassReturn")]
        public string updpass(string dlmc, string oldpwd, string newpwd) {
            object[] results = this.Invoke("updpass", new object[] {
                        dlmc,
                        oldpwd,
                        newpwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdpass(string dlmc, string oldpwd, string newpwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updpass", new object[] {
                        dlmc,
                        oldpwd,
                        newpwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endupdpass(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updpassAsync(string dlmc, string oldpwd, string newpwd) {
            this.updpassAsync(dlmc, oldpwd, newpwd, null);
        }
        
        /// <remarks/>
        public void updpassAsync(string dlmc, string oldpwd, string newpwd, object userState) {
            if ((this.updpassOperationCompleted == null)) {
                this.updpassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdpassOperationCompleted);
            }
            this.InvokeAsync("updpass", new object[] {
                        dlmc,
                        oldpwd,
                        newpwd}, this.updpassOperationCompleted, userState);
        }
        
        private void OnupdpassOperationCompleted(object arg) {
            if ((this.updpassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updpassCompleted(this, new updpassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getZdxxReturn")]
        public string getZdxx() {
            object[] results = this.Invoke("getZdxx", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetZdxx(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getZdxx", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetZdxx(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getZdxxAsync() {
            this.getZdxxAsync(null);
        }
        
        /// <remarks/>
        public void getZdxxAsync(object userState) {
            if ((this.getZdxxOperationCompleted == null)) {
                this.getZdxxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZdxxOperationCompleted);
            }
            this.InvokeAsync("getZdxx", new object[0], this.getZdxxOperationCompleted, userState);
        }
        
        private void OngetZdxxOperationCompleted(object arg) {
            if ((this.getZdxxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getZdxxCompleted(this, new getZdxxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getWjtdReturn")]
        public string getWjtd(string jdzdm) {
            object[] results = this.Invoke("getWjtd", new object[] {
                        jdzdm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetWjtd(string jdzdm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getWjtd", new object[] {
                        jdzdm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetWjtd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getWjtdAsync(string jdzdm) {
            this.getWjtdAsync(jdzdm, null);
        }
        
        /// <remarks/>
        public void getWjtdAsync(string jdzdm, object userState) {
            if ((this.getWjtdOperationCompleted == null)) {
                this.getWjtdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWjtdOperationCompleted);
            }
            this.InvokeAsync("getWjtd", new object[] {
                        jdzdm}, this.getWjtdOperationCompleted, userState);
        }
        
        private void OngetWjtdOperationCompleted(object arg) {
            if ((this.getWjtdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWjtdCompleted(this, new getWjtdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getZpgwcsReturn")]
        public string getZpgwcs(string jcz, string jcxdm, string jcxm) {
            object[] results = this.Invoke("getZpgwcs", new object[] {
                        jcz,
                        jcxdm,
                        jcxm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetZpgwcs(string jcz, string jcxdm, string jcxm, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getZpgwcs", new object[] {
                        jcz,
                        jcxdm,
                        jcxm}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetZpgwcs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getZpgwcsAsync(string jcz, string jcxdm, string jcxm) {
            this.getZpgwcsAsync(jcz, jcxdm, jcxm, null);
        }
        
        /// <remarks/>
        public void getZpgwcsAsync(string jcz, string jcxdm, string jcxm, object userState) {
            if ((this.getZpgwcsOperationCompleted == null)) {
                this.getZpgwcsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZpgwcsOperationCompleted);
            }
            this.InvokeAsync("getZpgwcs", new object[] {
                        jcz,
                        jcxdm,
                        jcxm}, this.getZpgwcsOperationCompleted, userState);
        }
        
        private void OngetZpgwcsOperationCompleted(object arg) {
            if ((this.getZpgwcsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getZpgwcsCompleted(this, new getZpgwcsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("uploadWjzpReturn")]
        public string uploadWjzp(string imgStr) {
            object[] results = this.Invoke("uploadWjzp", new object[] {
                        imgStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuploadWjzp(string imgStr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("uploadWjzp", new object[] {
                        imgStr}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnduploadWjzp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadWjzpAsync(string imgStr) {
            this.uploadWjzpAsync(imgStr, null);
        }
        
        /// <remarks/>
        public void uploadWjzpAsync(string imgStr, object userState) {
            if ((this.uploadWjzpOperationCompleted == null)) {
                this.uploadWjzpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadWjzpOperationCompleted);
            }
            this.InvokeAsync("uploadWjzp", new object[] {
                        imgStr}, this.uploadWjzpOperationCompleted, userState);
        }
        
        private void OnuploadWjzpOperationCompleted(object arg) {
            if ((this.uploadWjzpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadWjzpCompleted(this, new uploadWjzpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getWjzpReturn")]
        public string getWjzp(string lsh, string zplx) {
            object[] results = this.Invoke("getWjzp", new object[] {
                        lsh,
                        zplx});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetWjzp(string lsh, string zplx, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getWjzp", new object[] {
                        lsh,
                        zplx}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetWjzp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getWjzpAsync(string lsh, string zplx) {
            this.getWjzpAsync(lsh, zplx, null);
        }
        
        /// <remarks/>
        public void getWjzpAsync(string lsh, string zplx, object userState) {
            if ((this.getWjzpOperationCompleted == null)) {
                this.getWjzpOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWjzpOperationCompleted);
            }
            this.InvokeAsync("getWjzp", new object[] {
                        lsh,
                        zplx}, this.getWjzpOperationCompleted, userState);
        }
        
        private void OngetWjzpOperationCompleted(object arg) {
            if ((this.getWjzpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWjzpCompleted(this, new getWjzpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getBbhReturn")]
        public string getBbh() {
            object[] results = this.Invoke("getBbh", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBbh(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBbh", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetBbh(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBbhAsync() {
            this.getBbhAsync(null);
        }
        
        /// <remarks/>
        public void getBbhAsync(object userState) {
            if ((this.getBbhOperationCompleted == null)) {
                this.getBbhOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBbhOperationCompleted);
            }
            this.InvokeAsync("getBbh", new object[0], this.getBbhOperationCompleted, userState);
        }
        
        private void OngetBbhOperationCompleted(object arg) {
            if ((this.getBbhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBbhCompleted(this, new getBbhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("downLoadChunkReturn")]
        public string downLoadChunk(string bbh) {
            object[] results = this.Invoke("downLoadChunk", new object[] {
                        bbh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindownLoadChunk(string bbh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("downLoadChunk", new object[] {
                        bbh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddownLoadChunk(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downLoadChunkAsync(string bbh) {
            this.downLoadChunkAsync(bbh, null);
        }
        
        /// <remarks/>
        public void downLoadChunkAsync(string bbh, object userState) {
            if ((this.downLoadChunkOperationCompleted == null)) {
                this.downLoadChunkOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownLoadChunkOperationCompleted);
            }
            this.InvokeAsync("downLoadChunk", new object[] {
                        bbh}, this.downLoadChunkOperationCompleted, userState);
        }
        
        private void OndownLoadChunkOperationCompleted(object arg) {
            if ((this.downLoadChunkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downLoadChunkCompleted(this, new downLoadChunkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getJcxWjyhlbReturn")]
        public string getJcxWjyhlb(string jczdm, string yhlb) {
            object[] results = this.Invoke("getJcxWjyhlb", new object[] {
                        jczdm,
                        yhlb});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetJcxWjyhlb(string jczdm, string yhlb, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getJcxWjyhlb", new object[] {
                        jczdm,
                        yhlb}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetJcxWjyhlb(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getJcxWjyhlbAsync(string jczdm, string yhlb) {
            this.getJcxWjyhlbAsync(jczdm, yhlb, null);
        }
        
        /// <remarks/>
        public void getJcxWjyhlbAsync(string jczdm, string yhlb, object userState) {
            if ((this.getJcxWjyhlbOperationCompleted == null)) {
                this.getJcxWjyhlbOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJcxWjyhlbOperationCompleted);
            }
            this.InvokeAsync("getJcxWjyhlb", new object[] {
                        jczdm,
                        yhlb}, this.getJcxWjyhlbOperationCompleted, userState);
        }
        
        private void OngetJcxWjyhlbOperationCompleted(object arg) {
            if ((this.getJcxWjyhlbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJcxWjyhlbCompleted(this, new getJcxWjyhlbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("setPdabaReturn")]
        public string setPdaba(string brands, string model, string pdach, string fwzdm, string fwzmc) {
            object[] results = this.Invoke("setPdaba", new object[] {
                        brands,
                        model,
                        pdach,
                        fwzdm,
                        fwzmc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPdaba(string brands, string model, string pdach, string fwzdm, string fwzmc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPdaba", new object[] {
                        brands,
                        model,
                        pdach,
                        fwzdm,
                        fwzmc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetPdaba(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setPdabaAsync(string brands, string model, string pdach, string fwzdm, string fwzmc) {
            this.setPdabaAsync(brands, model, pdach, fwzdm, fwzmc, null);
        }
        
        /// <remarks/>
        public void setPdabaAsync(string brands, string model, string pdach, string fwzdm, string fwzmc, object userState) {
            if ((this.setPdabaOperationCompleted == null)) {
                this.setPdabaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPdabaOperationCompleted);
            }
            this.InvokeAsync("setPdaba", new object[] {
                        brands,
                        model,
                        pdach,
                        fwzdm,
                        fwzmc}, this.setPdabaOperationCompleted, userState);
        }
        
        private void OnsetPdabaOperationCompleted(object arg) {
            if ((this.setPdabaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPdabaCompleted(this, new setPdabaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getJczInfoReturn")]
        public string getJczInfo(string serverip, string serverport) {
            object[] results = this.Invoke("getJczInfo", new object[] {
                        serverip,
                        serverport});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetJczInfo(string serverip, string serverport, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getJczInfo", new object[] {
                        serverip,
                        serverport}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetJczInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getJczInfoAsync(string serverip, string serverport) {
            this.getJczInfoAsync(serverip, serverport, null);
        }
        
        /// <remarks/>
        public void getJczInfoAsync(string serverip, string serverport, object userState) {
            if ((this.getJczInfoOperationCompleted == null)) {
                this.getJczInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJczInfoOperationCompleted);
            }
            this.InvokeAsync("getJczInfo", new object[] {
                        serverip,
                        serverport}, this.getJczInfoOperationCompleted, userState);
        }
        
        private void OngetJczInfoOperationCompleted(object arg) {
            if ((this.getJczInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJczInfoCompleted(this, new getJczInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSerTimeReturn")]
        public string getSerTime() {
            object[] results = this.Invoke("getSerTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSerTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSerTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetSerTime(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSerTimeAsync() {
            this.getSerTimeAsync(null);
        }
        
        /// <remarks/>
        public void getSerTimeAsync(object userState) {
            if ((this.getSerTimeOperationCompleted == null)) {
                this.getSerTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSerTimeOperationCompleted);
            }
            this.InvokeAsync("getSerTime", new object[0], this.getSerTimeOperationCompleted, userState);
        }
        
        private void OngetSerTimeOperationCompleted(object arg) {
            if ((this.getSerTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSerTimeCompleted(this, new getSerTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("encodeUTF8Return")]
        public string encodeUTF8(string xmlDoc) {
            object[] results = this.Invoke("encodeUTF8", new object[] {
                        xmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginencodeUTF8(string xmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("encodeUTF8", new object[] {
                        xmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndencodeUTF8(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void encodeUTF8Async(string xmlDoc) {
            this.encodeUTF8Async(xmlDoc, null);
        }
        
        /// <remarks/>
        public void encodeUTF8Async(string xmlDoc, object userState) {
            if ((this.encodeUTF8OperationCompleted == null)) {
                this.encodeUTF8OperationCompleted = new System.Threading.SendOrPostCallback(this.OnencodeUTF8OperationCompleted);
            }
            this.InvokeAsync("encodeUTF8", new object[] {
                        xmlDoc}, this.encodeUTF8OperationCompleted, userState);
        }
        
        private void OnencodeUTF8OperationCompleted(object arg) {
            if ((this.encodeUTF8Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encodeUTF8Completed(this, new encodeUTF8CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSpsbxxReturn")]
        public string getSpsbxx(string jyjgbh, string jkxlh) {
            object[] results = this.Invoke("getSpsbxx", new object[] {
                        jyjgbh,
                        jkxlh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSpsbxx(string jyjgbh, string jkxlh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSpsbxx", new object[] {
                        jyjgbh,
                        jkxlh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetSpsbxx(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSpsbxxAsync(string jyjgbh, string jkxlh) {
            this.getSpsbxxAsync(jyjgbh, jkxlh, null);
        }
        
        /// <remarks/>
        public void getSpsbxxAsync(string jyjgbh, string jkxlh, object userState) {
            if ((this.getSpsbxxOperationCompleted == null)) {
                this.getSpsbxxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSpsbxxOperationCompleted);
            }
            this.InvokeAsync("getSpsbxx", new object[] {
                        jyjgbh,
                        jkxlh}, this.getSpsbxxOperationCompleted, userState);
        }
        
        private void OngetSpsbxxOperationCompleted(object arg) {
            if ((this.getSpsbxxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSpsbxxCompleted(this, new getSpsbxxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("isJkxlhReturn")]
        public int isJkxlh(string jyjgbh, string jkxlh) {
            object[] results = this.Invoke("isJkxlh", new object[] {
                        jyjgbh,
                        jkxlh});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisJkxlh(string jyjgbh, string jkxlh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isJkxlh", new object[] {
                        jyjgbh,
                        jkxlh}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndisJkxlh(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void isJkxlhAsync(string jyjgbh, string jkxlh) {
            this.isJkxlhAsync(jyjgbh, jkxlh, null);
        }
        
        /// <remarks/>
        public void isJkxlhAsync(string jyjgbh, string jkxlh, object userState) {
            if ((this.isJkxlhOperationCompleted == null)) {
                this.isJkxlhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisJkxlhOperationCompleted);
            }
            this.InvokeAsync("isJkxlh", new object[] {
                        jyjgbh,
                        jkxlh}, this.isJkxlhOperationCompleted, userState);
        }
        
        private void OnisJkxlhOperationCompleted(object arg) {
            if ((this.isJkxlhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isJkxlhCompleted(this, new isJkxlhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("getXydcListReturn")]
        public string getXydcList(string jyjgbh, string xyzl, string jkxlh) {
            object[] results = this.Invoke("getXydcList", new object[] {
                        jyjgbh,
                        xyzl,
                        jkxlh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetXydcList(string jyjgbh, string xyzl, string jkxlh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getXydcList", new object[] {
                        jyjgbh,
                        xyzl,
                        jkxlh}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetXydcList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXydcListAsync(string jyjgbh, string xyzl, string jkxlh) {
            this.getXydcListAsync(jyjgbh, xyzl, jkxlh, null);
        }
        
        /// <remarks/>
        public void getXydcListAsync(string jyjgbh, string xyzl, string jkxlh, object userState) {
            if ((this.getXydcListOperationCompleted == null)) {
                this.getXydcListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXydcListOperationCompleted);
            }
            this.InvokeAsync("getXydcList", new object[] {
                        jyjgbh,
                        xyzl,
                        jkxlh}, this.getXydcListOperationCompleted, userState);
        }
        
        private void OngetXydcListOperationCompleted(object arg) {
            if ((this.getXydcListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXydcListCompleted(this, new getXydcListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("endXydcZjReturn")]
        public string endXydcZj(string jyjgbh, string jkxlh, string xydcxml) {
            object[] results = this.Invoke("endXydcZj", new object[] {
                        jyjgbh,
                        jkxlh,
                        xydcxml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginendXydcZj(string jyjgbh, string jkxlh, string xydcxml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("endXydcZj", new object[] {
                        jyjgbh,
                        jkxlh,
                        xydcxml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndendXydcZj(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void endXydcZjAsync(string jyjgbh, string jkxlh, string xydcxml) {
            this.endXydcZjAsync(jyjgbh, jkxlh, xydcxml, null);
        }
        
        /// <remarks/>
        public void endXydcZjAsync(string jyjgbh, string jkxlh, string xydcxml, object userState) {
            if ((this.endXydcZjOperationCompleted == null)) {
                this.endXydcZjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnendXydcZjOperationCompleted);
            }
            this.InvokeAsync("endXydcZj", new object[] {
                        jyjgbh,
                        jkxlh,
                        xydcxml}, this.endXydcZjOperationCompleted, userState);
        }
        
        private void OnendXydcZjOperationCompleted(object arg) {
            if ((this.endXydcZjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.endXydcZjCompleted(this, new endXydcZjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("uploadXydcZjReturn")]
        public string uploadXydcZj(string jyjgbh, string jkxlh, string xydcxml) {
            object[] results = this.Invoke("uploadXydcZj", new object[] {
                        jyjgbh,
                        jkxlh,
                        xydcxml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuploadXydcZj(string jyjgbh, string jkxlh, string xydcxml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("uploadXydcZj", new object[] {
                        jyjgbh,
                        jkxlh,
                        xydcxml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnduploadXydcZj(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadXydcZjAsync(string jyjgbh, string jkxlh, string xydcxml) {
            this.uploadXydcZjAsync(jyjgbh, jkxlh, xydcxml, null);
        }
        
        /// <remarks/>
        public void uploadXydcZjAsync(string jyjgbh, string jkxlh, string xydcxml, object userState) {
            if ((this.uploadXydcZjOperationCompleted == null)) {
                this.uploadXydcZjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadXydcZjOperationCompleted);
            }
            this.InvokeAsync("uploadXydcZj", new object[] {
                        jyjgbh,
                        jkxlh,
                        xydcxml}, this.uploadXydcZjOperationCompleted, userState);
        }
        
        private void OnuploadXydcZjOperationCompleted(object arg) {
            if ((this.uploadXydcZjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadXydcZjCompleted(this, new uploadXydcZjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkXmEndReturn")]
        public string checkXmEnd(string jyjgbh, string jylsh, string jkxlh, string jyxm, string jycs) {
            object[] results = this.Invoke("checkXmEnd", new object[] {
                        jyjgbh,
                        jylsh,
                        jkxlh,
                        jyxm,
                        jycs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckXmEnd(string jyjgbh, string jylsh, string jkxlh, string jyxm, string jycs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkXmEnd", new object[] {
                        jyjgbh,
                        jylsh,
                        jkxlh,
                        jyxm,
                        jycs}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckXmEnd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkXmEndAsync(string jyjgbh, string jylsh, string jkxlh, string jyxm, string jycs) {
            this.checkXmEndAsync(jyjgbh, jylsh, jkxlh, jyxm, jycs, null);
        }
        
        /// <remarks/>
        public void checkXmEndAsync(string jyjgbh, string jylsh, string jkxlh, string jyxm, string jycs, object userState) {
            if ((this.checkXmEndOperationCompleted == null)) {
                this.checkXmEndOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckXmEndOperationCompleted);
            }
            this.InvokeAsync("checkXmEnd", new object[] {
                        jyjgbh,
                        jylsh,
                        jkxlh,
                        jyxm,
                        jycs}, this.checkXmEndOperationCompleted, userState);
        }
        
        private void OncheckXmEndOperationCompleted(object arg) {
            if ((this.checkXmEndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkXmEndCompleted(this, new checkXmEndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("uploadFileReturn")]
        public string uploadFile(string jyjgbh, string pdach, string jkxlh, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileNode, string fileNodeInfo) {
            object[] results = this.Invoke("uploadFile", new object[] {
                        jyjgbh,
                        pdach,
                        jkxlh,
                        fileNode,
                        fileNodeInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuploadFile(string jyjgbh, string pdach, string jkxlh, byte[] fileNode, string fileNodeInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("uploadFile", new object[] {
                        jyjgbh,
                        pdach,
                        jkxlh,
                        fileNode,
                        fileNodeInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnduploadFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadFileAsync(string jyjgbh, string pdach, string jkxlh, byte[] fileNode, string fileNodeInfo) {
            this.uploadFileAsync(jyjgbh, pdach, jkxlh, fileNode, fileNodeInfo, null);
        }
        
        /// <remarks/>
        public void uploadFileAsync(string jyjgbh, string pdach, string jkxlh, byte[] fileNode, string fileNodeInfo, object userState) {
            if ((this.uploadFileOperationCompleted == null)) {
                this.uploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadFileOperationCompleted);
            }
            this.InvokeAsync("uploadFile", new object[] {
                        jyjgbh,
                        pdach,
                        jkxlh,
                        fileNode,
                        fileNodeInfo}, this.uploadFileOperationCompleted, userState);
        }
        
        private void OnuploadFileOperationCompleted(object arg) {
            if ((this.uploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadFileCompleted(this, new uploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.jcjk.carry", ResponseNamespace="http://192.168.31.126:9080/jcjklw/services/jcjkService")]
        [return: System.Xml.Serialization.SoapElementAttribute("uploadFileEndReturn")]
        public string uploadFileEnd(string jyjgbh, string pdach, string jkxlh, string writeXmlDoc) {
            object[] results = this.Invoke("uploadFileEnd", new object[] {
                        jyjgbh,
                        pdach,
                        jkxlh,
                        writeXmlDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuploadFileEnd(string jyjgbh, string pdach, string jkxlh, string writeXmlDoc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("uploadFileEnd", new object[] {
                        jyjgbh,
                        pdach,
                        jkxlh,
                        writeXmlDoc}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnduploadFileEnd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadFileEndAsync(string jyjgbh, string pdach, string jkxlh, string writeXmlDoc) {
            this.uploadFileEndAsync(jyjgbh, pdach, jkxlh, writeXmlDoc, null);
        }
        
        /// <remarks/>
        public void uploadFileEndAsync(string jyjgbh, string pdach, string jkxlh, string writeXmlDoc, object userState) {
            if ((this.uploadFileEndOperationCompleted == null)) {
                this.uploadFileEndOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadFileEndOperationCompleted);
            }
            this.InvokeAsync("uploadFileEnd", new object[] {
                        jyjgbh,
                        pdach,
                        jkxlh,
                        writeXmlDoc}, this.uploadFileEndOperationCompleted, userState);
        }
        
        private void OnuploadFileEndOperationCompleted(object arg) {
            if ((this.uploadFileEndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadFileEndCompleted(this, new uploadFileEndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void HBwriteObjectOutCompletedEventHandler(object sender, HBwriteObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HBwriteObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HBwriteObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getXydcInfoCompletedEventHandler(object sender, getXydcInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXydcInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXydcInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void HBqueryObjectOutCompletedEventHandler(object sender, HBqueryObjectOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HBqueryObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HBqueryObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void checkUserCompletedEventHandler(object sender, checkUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void updpassCompletedEventHandler(object sender, updpassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updpassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updpassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getZdxxCompletedEventHandler(object sender, getZdxxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getZdxxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getZdxxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getWjtdCompletedEventHandler(object sender, getWjtdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWjtdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWjtdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getZpgwcsCompletedEventHandler(object sender, getZpgwcsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getZpgwcsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getZpgwcsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void uploadWjzpCompletedEventHandler(object sender, uploadWjzpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadWjzpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadWjzpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getWjzpCompletedEventHandler(object sender, getWjzpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWjzpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWjzpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getBbhCompletedEventHandler(object sender, getBbhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBbhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBbhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void downLoadChunkCompletedEventHandler(object sender, downLoadChunkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downLoadChunkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downLoadChunkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getJcxWjyhlbCompletedEventHandler(object sender, getJcxWjyhlbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getJcxWjyhlbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getJcxWjyhlbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void setPdabaCompletedEventHandler(object sender, setPdabaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPdabaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPdabaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getJczInfoCompletedEventHandler(object sender, getJczInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getJczInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getJczInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getSerTimeCompletedEventHandler(object sender, getSerTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSerTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSerTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void encodeUTF8CompletedEventHandler(object sender, encodeUTF8CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encodeUTF8CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encodeUTF8CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getSpsbxxCompletedEventHandler(object sender, getSpsbxxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSpsbxxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSpsbxxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void isJkxlhCompletedEventHandler(object sender, isJkxlhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isJkxlhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isJkxlhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void getXydcListCompletedEventHandler(object sender, getXydcListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXydcListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXydcListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void endXydcZjCompletedEventHandler(object sender, endXydcZjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class endXydcZjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal endXydcZjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void uploadXydcZjCompletedEventHandler(object sender, uploadXydcZjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadXydcZjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadXydcZjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void checkXmEndCompletedEventHandler(object sender, checkXmEndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkXmEndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkXmEndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void uploadFileCompletedEventHandler(object sender, uploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void uploadFileEndCompletedEventHandler(object sender, uploadFileEndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadFileEndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadFileEndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
