//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;


// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.gzvehicle.cn/")]
public partial class WKService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback writeObjectOutOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryObjectOutOperationCompleted;
    
    private System.Threading.SendOrPostCallback chaxunpicOperationCompleted;
    
    private System.Threading.SendOrPostCallback chaxunpicandtimeOperationCompleted;
    
    private System.Threading.SendOrPostCallback chaxunpicandtimeexOperationCompleted;
    
    private System.Threading.SendOrPostCallback getpicOperationCompleted;
    
    private System.Threading.SendOrPostCallback insertpicOperationCompleted;
    
    private System.Threading.SendOrPostCallback SavaCJTPOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendLoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendRefLoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback wkccOperationCompleted;
    
    private System.Threading.SendOrPostCallback getwkccOperationCompleted;
    
    private System.Threading.SendOrPostCallback getclxxOperationCompleted;
    
    private System.Threading.SendOrPostCallback zbzlOperationCompleted;
    
    /// <remarks/>
    public WKService() {
        this.Url = "http://localhost/Webs/Service.asmx";
    }
    public WKService(string url)
    {
        this.Url = url;
    }

    /// <remarks/>
    public event WKwriteObjectOutCompletedEventHandler writeObjectOutCompleted;
    
    /// <remarks/>
    public event WKqueryObjectOutCompletedEventHandler queryObjectOutCompleted;
    
    /// <remarks/>
    public event chaxunpicCompletedEventHandler chaxunpicCompleted;
    
    /// <remarks/>
    public event chaxunpicandtimeCompletedEventHandler chaxunpicandtimeCompleted;
    
    /// <remarks/>
    public event chaxunpicandtimeexCompletedEventHandler chaxunpicandtimeexCompleted;
    
    /// <remarks/>
    public event getpicCompletedEventHandler getpicCompleted;
    
    /// <remarks/>
    public event insertpicCompletedEventHandler insertpicCompleted;
    
    /// <remarks/>
    public event SavaCJTPCompletedEventHandler SavaCJTPCompleted;
    
    /// <remarks/>
    public event SendLoginCompletedEventHandler SendLoginCompleted;
    
    /// <remarks/>
    public event SendRefLoginCompletedEventHandler SendRefLoginCompleted;
    
    /// <remarks/>
    public event wkccCompletedEventHandler wkccCompleted;
    
    /// <remarks/>
    public event getwkccCompletedEventHandler getwkccCompleted;
    
    /// <remarks/>
    public event getclxxCompletedEventHandler getclxxCompleted;
    
    /// <remarks/>
    public event zbzlCompletedEventHandler zbzlCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/writeObjectOut", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string writeObjectOut(string xtlb, string jkxlh, string jkid, string WriteXmlDoc)
    {
        object[] results = this.Invoke("writeObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    WriteXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginwriteObjectOut(string xtlb, string jkxlh, string jkid, string WriteXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("writeObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    WriteXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndwriteObjectOut(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string WriteXmlDoc) {
        this.writeObjectOutAsync(xtlb, jkxlh, jkid, WriteXmlDoc, null);
    }
    
    /// <remarks/>
    public void writeObjectOutAsync(string xtlb, string jkxlh, string jkid, string WriteXmlDoc, object userState) {
        if ((this.writeObjectOutOperationCompleted == null)) {
            this.writeObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwriteObjectOutOperationCompleted);
        }
        this.InvokeAsync("writeObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    WriteXmlDoc}, this.writeObjectOutOperationCompleted, userState);
    }
    
    private void OnwriteObjectOutOperationCompleted(object arg) {
        if ((this.writeObjectOutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.writeObjectOutCompleted(this, new WKwriteObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/queryObjectOut", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string queryObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc)
    {
        object[] results = this.Invoke("queryObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndqueryObjectOut(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        this.queryObjectOutAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
    }
    
    /// <remarks/>
    public void queryObjectOutAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
        if ((this.queryObjectOutOperationCompleted == null)) {
            this.queryObjectOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryObjectOutOperationCompleted);
        }
        this.InvokeAsync("queryObjectOut", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, this.queryObjectOutOperationCompleted, userState);
    }
    
    private void OnqueryObjectOutOperationCompleted(object arg) {
        if ((this.queryObjectOutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryObjectOutCompleted(this, new WKqueryObjectOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/chaxunpic", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string chaxunpic(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        object[] results = this.Invoke("chaxunpic", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginchaxunpic(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("chaxunpic", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endchaxunpic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void chaxunpicAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        this.chaxunpicAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
    }
    
    /// <remarks/>
    public void chaxunpicAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
        if ((this.chaxunpicOperationCompleted == null)) {
            this.chaxunpicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchaxunpicOperationCompleted);
        }
        this.InvokeAsync("chaxunpic", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, this.chaxunpicOperationCompleted, userState);
    }
    
    private void OnchaxunpicOperationCompleted(object arg) {
        if ((this.chaxunpicCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.chaxunpicCompleted(this, new chaxunpicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/chaxunpicandtime", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string chaxunpicandtime(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        object[] results = this.Invoke("chaxunpicandtime", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginchaxunpicandtime(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("chaxunpicandtime", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endchaxunpicandtime(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void chaxunpicandtimeAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        this.chaxunpicandtimeAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
    }
    
    /// <remarks/>
    public void chaxunpicandtimeAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
        if ((this.chaxunpicandtimeOperationCompleted == null)) {
            this.chaxunpicandtimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchaxunpicandtimeOperationCompleted);
        }
        this.InvokeAsync("chaxunpicandtime", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, this.chaxunpicandtimeOperationCompleted, userState);
    }
    
    private void OnchaxunpicandtimeOperationCompleted(object arg) {
        if ((this.chaxunpicandtimeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.chaxunpicandtimeCompleted(this, new chaxunpicandtimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/chaxunpicandtimeex", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string chaxunpicandtimeex(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        object[] results = this.Invoke("chaxunpicandtimeex", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginchaxunpicandtimeex(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("chaxunpicandtimeex", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endchaxunpicandtimeex(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void chaxunpicandtimeexAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        this.chaxunpicandtimeexAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
    }
    
    /// <remarks/>
    public void chaxunpicandtimeexAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
        if ((this.chaxunpicandtimeexOperationCompleted == null)) {
            this.chaxunpicandtimeexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchaxunpicandtimeexOperationCompleted);
        }
        this.InvokeAsync("chaxunpicandtimeex", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, this.chaxunpicandtimeexOperationCompleted, userState);
    }
    
    private void OnchaxunpicandtimeexOperationCompleted(object arg) {
        if ((this.chaxunpicandtimeexCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.chaxunpicandtimeexCompleted(this, new chaxunpicandtimeexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/getpic", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getpic(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        object[] results = this.Invoke("getpic", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begingetpic(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getpic", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endgetpic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getpicAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
        this.getpicAsync(xtlb, jkxlh, jkid, QueryXmlDoc, null);
    }
    
    /// <remarks/>
    public void getpicAsync(string xtlb, string jkxlh, string jkid, string QueryXmlDoc, object userState) {
        if ((this.getpicOperationCompleted == null)) {
            this.getpicOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetpicOperationCompleted);
        }
        this.InvokeAsync("getpic", new object[] {
                    xtlb,
                    jkxlh,
                    jkid,
                    QueryXmlDoc}, this.getpicOperationCompleted, userState);
    }
    
    private void OngetpicOperationCompleted(object arg) {
        if ((this.getpicCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getpicCompleted(this, new getpicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/insertpic", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string insertpic(string QueryXmlDoc) {
        object[] results = this.Invoke("insertpic", new object[] {
                    QueryXmlDoc});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begininsertpic(string QueryXmlDoc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("insertpic", new object[] {
                    QueryXmlDoc}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endinsertpic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void insertpicAsync(string QueryXmlDoc) {
        this.insertpicAsync(QueryXmlDoc, null);
    }
    
    /// <remarks/>
    public void insertpicAsync(string QueryXmlDoc, object userState) {
        if ((this.insertpicOperationCompleted == null)) {
            this.insertpicOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertpicOperationCompleted);
        }
        this.InvokeAsync("insertpic", new object[] {
                    QueryXmlDoc}, this.insertpicOperationCompleted, userState);
    }
    
    private void OninsertpicOperationCompleted(object arg) {
        if ((this.insertpicCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.insertpicCompleted(this, new insertpicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/SavaCJTP", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SavaCJTP(string name, string base64) {
        object[] results = this.Invoke("SavaCJTP", new object[] {
                    name,
                    base64});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSavaCJTP(string name, string base64, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SavaCJTP", new object[] {
                    name,
                    base64}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSavaCJTP(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SavaCJTPAsync(string name, string base64) {
        this.SavaCJTPAsync(name, base64, null);
    }
    
    /// <remarks/>
    public void SavaCJTPAsync(string name, string base64, object userState) {
        if ((this.SavaCJTPOperationCompleted == null)) {
            this.SavaCJTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavaCJTPOperationCompleted);
        }
        this.InvokeAsync("SavaCJTP", new object[] {
                    name,
                    base64}, this.SavaCJTPOperationCompleted, userState);
    }
    
    private void OnSavaCJTPOperationCompleted(object arg) {
        if ((this.SavaCJTPCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SavaCJTPCompleted(this, new SavaCJTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/SendLogin", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SendLogin(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string ygddtz, string zxzxjxs, string jkxlh) {
        object[] results = this.Invoke("SendLogin", new object[] {
                    jylsh,
                    jyjgbh,
                    hphm,
                    hpzl,
                    jyxm,
                    dly,
                    ygddtz,
                    zxzxjxs,
                    jkxlh});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendLogin(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string ygddtz, string zxzxjxs, string jkxlh, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendLogin", new object[] {
                    jylsh,
                    jyjgbh,
                    hphm,
                    hpzl,
                    jyxm,
                    dly,
                    ygddtz,
                    zxzxjxs,
                    jkxlh}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSendLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SendLoginAsync(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string ygddtz, string zxzxjxs, string jkxlh) {
        this.SendLoginAsync(jylsh, jyjgbh, hphm, hpzl, jyxm, dly, ygddtz, zxzxjxs, jkxlh, null);
    }
    
    /// <remarks/>
    public void SendLoginAsync(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string ygddtz, string zxzxjxs, string jkxlh, object userState) {
        if ((this.SendLoginOperationCompleted == null)) {
            this.SendLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendLoginOperationCompleted);
        }
        this.InvokeAsync("SendLogin", new object[] {
                    jylsh,
                    jyjgbh,
                    hphm,
                    hpzl,
                    jyxm,
                    dly,
                    ygddtz,
                    zxzxjxs,
                    jkxlh}, this.SendLoginOperationCompleted, userState);
    }
    
    private void OnSendLoginOperationCompleted(object arg) {
        if ((this.SendLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendLoginCompleted(this, new SendLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/SendRefLogin", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SendRefLogin(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string jycs, string jkxlh) {
        object[] results = this.Invoke("SendRefLogin", new object[] {
                    jylsh,
                    jyjgbh,
                    hphm,
                    hpzl,
                    jyxm,
                    dly,
                    jycs,
                    jkxlh});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendRefLogin(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string jycs, string jkxlh, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendRefLogin", new object[] {
                    jylsh,
                    jyjgbh,
                    hphm,
                    hpzl,
                    jyxm,
                    dly,
                    jycs,
                    jkxlh}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSendRefLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SendRefLoginAsync(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string jycs, string jkxlh) {
        this.SendRefLoginAsync(jylsh, jyjgbh, hphm, hpzl, jyxm, dly, jycs, jkxlh, null);
    }
    
    /// <remarks/>
    public void SendRefLoginAsync(string jylsh, string jyjgbh, string hphm, string hpzl, string jyxm, string dly, string jycs, string jkxlh, object userState) {
        if ((this.SendRefLoginOperationCompleted == null)) {
            this.SendRefLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendRefLoginOperationCompleted);
        }
        this.InvokeAsync("SendRefLogin", new object[] {
                    jylsh,
                    jyjgbh,
                    hphm,
                    hpzl,
                    jyxm,
                    dly,
                    jycs,
                    jkxlh}, this.SendRefLoginOperationCompleted, userState);
    }
    
    private void OnSendRefLoginOperationCompleted(object arg) {
        if ((this.SendRefLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendRefLoginCompleted(this, new SendRefLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/wkcc", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string wkcc(string jylsh, string xml, string sbz)
    {
        object[] results = this.Invoke("wkcc", new object[] {
                    jylsh,
                    xml,
                    sbz});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginwkcc(string jylsh, string xml, string sbz, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("wkcc", new object[] {
                    jylsh,
                    xml,
                    sbz}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endwkcc(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void wkccAsync(string jylsh, string xml, string sbz) {
        this.wkccAsync(jylsh, xml, sbz, null);
    }
    
    /// <remarks/>
    public void wkccAsync(string jylsh, string xml, string sbz, object userState) {
        if ((this.wkccOperationCompleted == null)) {
            this.wkccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwkccOperationCompleted);
        }
        this.InvokeAsync("wkcc", new object[] {
                    jylsh,
                    xml,
                    sbz}, this.wkccOperationCompleted, userState);
    }
    
    private void OnwkccOperationCompleted(object arg) {
        if ((this.wkccCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.wkccCompleted(this, new wkccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/getwkcc", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getwkcc(string jylsh) {
        object[] results = this.Invoke("getwkcc", new object[] {
                    jylsh});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begingetwkcc(string jylsh, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getwkcc", new object[] {
                    jylsh}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endgetwkcc(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getwkccAsync(string jylsh) {
        this.getwkccAsync(jylsh, null);
    }
    
    /// <remarks/>
    public void getwkccAsync(string jylsh, object userState) {
        if ((this.getwkccOperationCompleted == null)) {
            this.getwkccOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetwkccOperationCompleted);
        }
        this.InvokeAsync("getwkcc", new object[] {
                    jylsh}, this.getwkccOperationCompleted, userState);
    }
    
    private void OngetwkccOperationCompleted(object arg) {
        if ((this.getwkccCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getwkccCompleted(this, new getwkccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/getclxx", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string getclxx(string shphm, string shpzl)
    {
        object[] results = this.Invoke("getclxx", new object[] {
                    shphm,
                    shpzl});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begingetclxx(string shphm, string shpzl, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getclxx", new object[] {
                    shphm,
                    shpzl}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endgetclxx(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getclxxAsync(string shphm, string shpzl) {
        this.getclxxAsync(shphm, shpzl, null);
    }
    
    /// <remarks/>
    public void getclxxAsync(string shphm, string shpzl, object userState) {
        if ((this.getclxxOperationCompleted == null)) {
            this.getclxxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetclxxOperationCompleted);
        }
        this.InvokeAsync("getclxx", new object[] {
                    shphm,
                    shpzl}, this.getclxxOperationCompleted, userState);
    }
    
    private void OngetclxxOperationCompleted(object arg) {
        if ((this.getclxxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getclxxCompleted(this, new getclxxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gzvehicle.cn/zbzl", RequestNamespace="http://www.gzvehicle.cn/", ResponseNamespace="http://www.gzvehicle.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string zbzl(string jylsh, string xml, string sbz) {
        object[] results = this.Invoke("zbzl", new object[] {
                    jylsh,
                    xml,
                    sbz});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginzbzl(string jylsh, string xml, string sbz, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("zbzl", new object[] {
                    jylsh,
                    xml,
                    sbz}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endzbzl(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void zbzlAsync(string jylsh, string xml, string sbz) {
        this.zbzlAsync(jylsh, xml, sbz, null);
    }
    
    /// <remarks/>
    public void zbzlAsync(string jylsh, string xml, string sbz, object userState) {
        if ((this.zbzlOperationCompleted == null)) {
            this.zbzlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnzbzlOperationCompleted);
        }
        this.InvokeAsync("zbzl", new object[] {
                    jylsh,
                    xml,
                    sbz}, this.zbzlOperationCompleted, userState);
    }
    
    private void OnzbzlOperationCompleted(object arg) {
        if ((this.zbzlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.zbzlCompleted(this, new zbzlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void WKwriteObjectOutCompletedEventHandler(object sender, WKwriteObjectOutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WKwriteObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal WKwriteObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void WKqueryObjectOutCompletedEventHandler(object sender, WKqueryObjectOutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WKqueryObjectOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal WKqueryObjectOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void chaxunpicCompletedEventHandler(object sender, chaxunpicCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class chaxunpicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal chaxunpicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void chaxunpicandtimeCompletedEventHandler(object sender, chaxunpicandtimeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class chaxunpicandtimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal chaxunpicandtimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void chaxunpicandtimeexCompletedEventHandler(object sender, chaxunpicandtimeexCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class chaxunpicandtimeexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal chaxunpicandtimeexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getpicCompletedEventHandler(object sender, getpicCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getpicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getpicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void insertpicCompletedEventHandler(object sender, insertpicCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class insertpicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal insertpicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SavaCJTPCompletedEventHandler(object sender, SavaCJTPCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SavaCJTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SavaCJTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SendLoginCompletedEventHandler(object sender, SendLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void SendRefLoginCompletedEventHandler(object sender, SendRefLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendRefLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendRefLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void wkccCompletedEventHandler(object sender, wkccCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class wkccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal wkccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getwkccCompletedEventHandler(object sender, getwkccCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getwkccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getwkccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getclxxCompletedEventHandler(object sender, getclxxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getclxxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getclxxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void zbzlCompletedEventHandler(object sender, zbzlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class zbzlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal zbzlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
